### ISSUE TITLE
Enhance logging function

### ISSUE THREAD

**Issue by excute** [Excute/botchi-go#7]
## TODO

- [ ] Implement login, logout event log
- [ ] Get environment variable at `main` package(cmd/bot), not `logger` package
- [ ] Refine functions architecture
